### ISSUE TITLE
Unnecessary? Select variant

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-livecore#1]
https://github.com/bitfocus/companion-module-livecore/blob/6c948feee1235aa888c71f8adec53e20ff8cfb45/analogway_livecore.js#L159

Why do people have to choose the variant? The module does not seem to use this data for anything?

**Comment by dnmeid** [comment]
correct, the usage of this dropdown is not implemented yet but will be later (same in pds)
