### ISSUE TITLE
Problems to connect companion to Livecore Nextstage 0802-4k

### ISSUE THREAD

**Issue by pedrag8** [bitfocus/companion-module-livecore#5]
Hi 
I am having some problems to connect companion to Livecore Nextstage 0802-4k 
I am entering the right ip address and the right port 10600 for third party control, but nothing 
the error in the log is:
16. 15:02:11 instance(livecore): Network error: connect ETIMEDOUT 168.254.43.60:10600
16. 15:01:48 instance(livecore): Network error: connect ETIMEDOUT 168.254.43.60:10600

and before:
16. 14:26:13 instance(livecore): Network error: connect EADDRNOTAVAIL 168.254.43.60 - Local (0.0.0.0:55938)

if someone can help me it should great!

**Comment by dnmeid** [comment]
This is for sure not a problem with the module but with your network or network settings.
First make sure you can ping that ip and if that works use a terminal (e.g. putty if you're on a pc) to connect to the nextage with the port 10600. Only if get to the shell of the Nextage with the terminal but are not able to connect with companion at the same time come back here.

**Comment by pedrag8** [comment]
Hi!
Thanks a lot for your reply, in fact I found the problem, it was something
wrong with the firewall settings, then I also changed all the network
cables because I suspect too from that side, and know it working perfectly!
Sorry I didn't mute the thread, just because I was and still very busy in
this work, tomorrow I will do !
Thanks a lot !


Il sab 21 set 2019, 22:29 dnmeid <notifications@github.com> ha scritto:
